server:
    applicationConnectors:
    -   type: http
        port: 8080
    -   type: https
        port: 8843
    adminConnectors:
    -   type: http
        port: 8081
    -   type: https
        port: 8444